chore: update coverage threshold

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -53,7 +53,7 @@ jobs:
         run: |
           coverage=$(go tool cover -func=coverage.out | grep total: | awk '{print $3}' | sed 's/%//')
           echo "Coverage: $coverage%"
-#          if [ "$(echo "$coverage < 60" | bc)" -eq 1 ]; then
-#            echo "Coverage is below 60%. Failing the build."
-#            exit 1
-#          fi
+          if [ "$(echo "$coverage < 55" | bc)" -eq 1 ]; then
+            echo "Coverage is below 60%. Failing the build."
+            exit 1
+          fi
